services:
    ehdev_basics.form.type.oro_user_email_select:
        class: EHDev\BasicsBundle\Form\Type\OroUserEmailOriginSelectType
        tags:
            - { name: form.type, alias: ehdev_oro_user_email_origin_select }
            - { name: form.type, alias: EHDev\BasicsBundle\Form\Type\OroUserEmailOriginSelectType }

    ehdev_basics.form.type.oro_mailbox_select:
        class: EHDev\BasicsBundle\Form\Type\OroMailboxSelectType
        tags:
            - { name: form.type, alias: ehdev_oro_mailbox_select }
            - { name: form.type, alias: EHDev\BasicsBundle\Form\Type\OroMailboxSelectType }

    ehdev_basics.form.type.oro_username_choice:
        class: EHDev\BasicsBundle\Form\Type\OroUsernameChoiceType
        arguments: ["@oro_entity.doctrine_helper"]
        tags:
            - { name: form.type, alias: EHDev\BasicsBundle\Form\Type\OroUsernameChoiceType }

    ehdev_basics.form.type.oro_organization_choice:
        class: EHDev\BasicsBundle\Form\Type\OroOrganizationChoiceType
        tags:
            - { name: form.type, alias: EHDev\BasicsBundle\Form\Type\OroOrganizationChoiceType }


    ehdev_basics.form.extension.text_filter_type:
        class: EHDev\BasicsBundle\Form\Extension\TextFilterTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\FilterBundle\Form\Type\Filter\TextFilterType }

    ehdev_basics.form.extension.number_filter_type:
        class: EHDev\BasicsBundle\Form\Extension\NumberFilterTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType }

    ehdev_basics.form.extension.number_range_filter_type:
        class: EHDev\BasicsBundle\Form\Extension\NumberRangeFilterTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberRangeFilterType }

    ehdev_basics.form.extension.date_range_filter_type:
        class: EHDev\BasicsBundle\Form\Extension\DateRangeFilterTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\FilterBundle\Form\Type\Filter\DateRangeFilterType }
